---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 744777770970976256-aP3BMtd8iJRIB0GWjrfPIv6iOGmqBtD
:access_token_secret: bkxfn1kYYX3KnYGeDdaToh1zLhGRwKBAWqq0IEepro98Q
